const clean=(v:unknown,max=8000)=>String(v??'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim().slice(0,max);
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
export interface WebEvidence{title:string;url:string;snippet:string;source:string;publishedAt?:string;score:number;storyKey:string}
export interface ResearchResult{ok:boolean;query:string;kind:'news'|'web';evidence:WebEvidence[];sources:Array<{title:string;url:string}>;reason:string;latencyMs:number}
function safeHttpUrl(raw:string){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return'';if(['localhost','127.0.0.1','0.0.0.0','::1'].includes(u.hostname))return'';return u.href}catch{return''}}
function storyKey(title:string){return clean(title,300).toLocaleLowerCase().replace(/[^\p{L}\p{M}\p{N}]+/gu,' ').split(/\s+/).filter(x=>x.length>1).slice(0,10).sort().join('|')}
function rank(items:WebEvidence[],limit:number){const seen=new Set<string>(),out:WebEvidence[]=[];for(const item of items.sort((a,b)=>b.score-a.score)){const key=item.storyKey||storyKey(item.title);if(!key||seen.has(key))continue;seen.add(key);out.push(item);if(out.length>=limit)break}return out}
function googleNewsUrl(q:string){return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=th&gl=TH&ceid=TH:th`}
function parseNewsRss(xml:string):WebEvidence[]{const out:WebEvidence[]=[];const blocks=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];for(const block of blocks.slice(0,30)){const title=decode(block.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),url=safeHttpUrl(decode(block.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||'')),description=decode(block.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||''),source=decode(block.match(/<source[^>]*>([\s\S]*?)<\/source>/i)?.[1]||'Google News'),publishedAt=decode(block.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)?.[1]||'');if(!title||!url)continue;const age=publishedAt?Math.max(0,(Date.now()-Date.parse(publishedAt))/3600000):48;const freshness=Math.max(0,35-Math.min(35,age/2));out.push({title,url,snippet:description,source,publishedAt,score:60+freshness,storyKey:storyKey(title)})}return out}
function ddgTarget(href:string){try{const raw=decode(href);const absolute=raw.startsWith('//')?'https:'+raw:raw.startsWith('/')?'https://duckduckgo.com'+raw:raw;const u=new URL(absolute);if(u.hostname.endsWith('duckduckgo.com')&&u.pathname.startsWith('/l/')){const target=u.searchParams.get('uddg');return target?safeHttpUrl(decodeURIComponent(target)):''}return safeHttpUrl(absolute)}catch{return''}}
function parseDdg(html:string):WebEvidence[]{const out:WebEvidence[]=[];const blocks=html.split(/<div class="result results_links[^>]*>/i).slice(1,25);for(const block of blocks){const a=block.match(/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=ddgTarget(a[1]!),title=decode(a[2]!),snippet=decode(block.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||'');if(!url||!title)continue;let source='';try{source=new URL(url).hostname.replace(/^www\./,'')}catch{}out.push({title,url,snippet,source,score:55,storyKey:storyKey(title)})}return out}
async function fetchText(fetcher:typeof fetch,url:string,timeout=7000){const controller=new AbortController(),id=setTimeout(()=>controller.abort(),timeout);try{const r=await fetcher(url,{headers:{accept:'text/html,application/rss+xml,application/xml;q=0.9,*/*;q=0.8','user-agent':'CeoKnowledge/2.0 (+public research)'},signal:controller.signal});if(!r.ok)throw new Error(`HTTP_${r.status}`);return(await r.text()).slice(0,500000)}finally{clearTimeout(id)}}
export async function researchWeb(query:string,options:{kind?:'news'|'web';limit?:number;fetcher?:typeof fetch}={}):Promise<ResearchResult>{const started=Date.now(),q=clean(query,600),kind=options.kind||(/ข่าว|news/i.test(q)?'news':'web'),limit=Math.max(1,Math.min(10,options.limit||5)),fetcher=options.fetcher||fetch;if(!q)return{ok:false,query:q,kind,evidence:[],sources:[],reason:'QUERY_REQUIRED',latencyMs:0};try{let evidence:WebEvidence[]=[];if(kind==='news'){const xml=await fetchText(fetcher,googleNewsUrl(q));evidence=parseNewsRss(xml);if(evidence.length<limit){const html=await fetchText(fetcher,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`).catch(()=> '');evidence.push(...parseDdg(html).map(x=>({...x,score:x.score-5})))}}else{const html=await fetchText(fetcher,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`);evidence=parseDdg(html)}const chosen=rank(evidence,limit);return{ok:chosen.length>0,query:q,kind,evidence:chosen,sources:chosen.map(x=>({title:x.title,url:x.url})),reason:chosen.length?'READY':'NO_RESULTS',latencyMs:Date.now()-started}}catch(error:any){return{ok:false,query:q,kind,evidence:[],sources:[],reason:`SEARCH_FAILED:${clean(error?.message||error,160)}`,latencyMs:Date.now()-started}}}
