const clean=(v:unknown,max=8000)=>String(v??'').replace(/\u0000/g,'').replace(/\s+/g,' ').trim().slice(0,max);
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
export interface WebEvidence{title:string;url:string;snippet:string;source:string;publishedAt?:string;score:number;storyKey:string}
export interface ResearchResult{ok:boolean;query:string;kind:'news'|'web';evidence:WebEvidence[];sources:Array<{title:string;url:string}>;reason:string;latencyMs:number;cache:'hit'|'miss';attempts:number;sourceDiversity:number;crossChecked:boolean}
type CacheEntry={expiresAt:number;value:ResearchResult};
const cache=new Map<string,CacheEntry>();
const telemetry={requests:0,cacheHits:0,success:0,failures:0,retries:0,lastLatencyMs:0,lastReason:'',lastAt:''};
export function researchTelemetry(){return{...telemetry,cacheSize:cache.size,hitRate:telemetry.requests?Math.round((telemetry.cacheHits/telemetry.requests)*1000)/10:0}}
export function clearResearchCache(){cache.clear()}
function cacheKey(q:string,kind:string,limit:number){return `${kind}|${limit}|${q.toLocaleLowerCase()}`}
function safeHttpUrl(raw:string){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return'';if(['localhost','127.0.0.1','0.0.0.0','::1'].includes(u.hostname))return'';return u.href}catch{return''}}
function storyKey(title:string){return clean(title,300).toLocaleLowerCase().replace(/[^\p{L}\p{M}\p{N}]+/gu,' ').split(/\s+/).filter(x=>x.length>1).slice(0,10).sort().join('|')}
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return''}}
function rank(items:WebEvidence[],limit:number){const seenStory=new Set<string>(),seenUrl=new Set<string>(),out:WebEvidence[]=[];for(const item of items.sort((a,b)=>b.score-a.score)){const key=item.storyKey||storyKey(item.title),u=item.url.replace(/[?#].*$/,'');if(!key||seenStory.has(key)||seenUrl.has(u))continue;seenStory.add(key);seenUrl.add(u);out.push(item);if(out.length>=limit)break}return out}
function googleNewsUrl(q:string){return `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=th&gl=TH&ceid=TH:th`}
function parseNewsRss(xml:string):WebEvidence[]{const out:WebEvidence[]=[];const blocks=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];for(const block of blocks.slice(0,40)){const title=decode(block.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),url=safeHttpUrl(decode(block.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||'')),description=decode(block.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||''),source=decode(block.match(/<source[^>]*>([\s\S]*?)<\/source>/i)?.[1]||'Google News'),publishedAt=decode(block.match(/<pubDate>([\s\S]*?)<\/pubDate>/i)?.[1]||'');if(!title||!url)continue;const parsed=publishedAt?Date.parse(publishedAt):NaN,age=Number.isFinite(parsed)?Math.max(0,(Date.now()-parsed)/3600000):48,freshness=Math.max(0,35-Math.min(35,age/2));out.push({title,url,snippet:description,source,publishedAt,score:60+freshness,storyKey:storyKey(title)})}return out}
function ddgTarget(href:string){try{const raw=decode(href);const absolute=raw.startsWith('//')?'https:'+raw:raw.startsWith('/')?'https://duckduckgo.com'+raw:raw;const u=new URL(absolute);if(u.hostname.endsWith('duckduckgo.com')&&u.pathname.startsWith('/l/')){const target=u.searchParams.get('uddg');return target?safeHttpUrl(decodeURIComponent(target)):''}return safeHttpUrl(absolute)}catch{return''}}
function parseDdg(html:string):WebEvidence[]{const out:WebEvidence[]=[];const blocks=html.split(/<div class="result results_links[^>]*>/i).slice(1,30);for(const block of blocks){const a=block.match(/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=ddgTarget(a[1]!),title=decode(a[2]!),snippet=decode(block.match(/class="result__snippet"[^>]*>([\s\S]*?)<\/a>/i)?.[1]||'');if(!url||!title)continue;out.push({title,url,snippet,source:host(url),score:55,storyKey:storyKey(title)})}return out}
async function fetchTextOnce(fetcher:typeof fetch,url:string,timeout=7000){const controller=new AbortController(),id=setTimeout(()=>controller.abort(),timeout);try{const r=await fetcher(url,{headers:{accept:'text/html,application/rss+xml,application/xml;q=0.9,*/*;q=0.8','user-agent':'CeoKnowledge/2.0 (+public research)'},signal:controller.signal});if(!r.ok)throw new Error(`HTTP_${r.status}`);return(await r.text()).slice(0,500000)}finally{clearTimeout(id)}}
async function fetchText(fetcher:typeof fetch,url:string,timeout=7000,retries=1){let last:any=null;for(let attempt=0;attempt<=retries;attempt++){try{return{body:await fetchTextOnce(fetcher,url,timeout),attempts:attempt+1}}catch(error:any){last=error;if(attempt<retries){telemetry.retries++;await new Promise(r=>setTimeout(r,120*(attempt+1)))}}}throw last||new Error('FETCH_FAILED')}
function diversity(items:WebEvidence[]){return new Set(items.map(x=>x.source||host(x.url)).filter(Boolean)).size}
export async function researchWeb(query:string,options:{kind?:'news'|'web';limit?:number;fetcher?:typeof fetch;cacheTtlMs?:number;retries?:number;disableCache?:boolean}={}):Promise<ResearchResult>{const started=Date.now(),q=clean(query,600),kind=options.kind||(/ข่าว|news/i.test(q)?'news':'web'),limit=Math.max(1,Math.min(10,options.limit||5)),fetcher=options.fetcher||fetch,ttl=Math.max(0,Math.min(300000,options.cacheTtlMs??(kind==='news'?45000:120000))),key=cacheKey(q,kind,limit);telemetry.requests++;if(!q)return{ok:false,query:q,kind,evidence:[],sources:[],reason:'QUERY_REQUIRED',latencyMs:0,cache:'miss',attempts:0,sourceDiversity:0,crossChecked:false};if(!options.disableCache){const hit=cache.get(key);if(hit&&hit.expiresAt>Date.now()){telemetry.cacheHits++;const value={...hit.value,cache:'hit' as const,latencyMs:Date.now()-started};telemetry.lastLatencyMs=value.latencyMs;telemetry.lastReason=value.reason;telemetry.lastAt=new Date().toISOString();return value}if(hit)cache.delete(key)}let attempts=0;try{let evidence:WebEvidence[]=[];if(kind==='news'){const primary=await fetchText(fetcher,googleNewsUrl(q),7000,options.retries??1);attempts+=primary.attempts;evidence=parseNewsRss(primary.body);const htmlResult=await fetchText(fetcher,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,7000,options.retries??1).catch(()=>null);if(htmlResult){attempts+=htmlResult.attempts;evidence.push(...parseDdg(htmlResult.body).map(x=>({...x,score:x.score-5})))}}else{const html=await fetchText(fetcher,`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,7000,options.retries??1);attempts+=html.attempts;evidence=parseDdg(html.body)}const chosen=rank(evidence,limit),sourceDiversity=diversity(chosen),result:ResearchResult={ok:chosen.length>0,query:q,kind,evidence:chosen,sources:chosen.map(x=>({title:x.title,url:x.url})),reason:chosen.length?'READY':'NO_RESULTS',latencyMs:Date.now()-started,cache:'miss',attempts,sourceDiversity,crossChecked:chosen.length>1&&sourceDiversity>1};if(result.ok){telemetry.success++;if(ttl>0&&!options.disableCache){cache.set(key,{expiresAt:Date.now()+ttl,value:result});if(cache.size>80){const first=cache.keys().next().value;if(first)cache.delete(first)}}}else telemetry.failures++;telemetry.lastLatencyMs=result.latencyMs;telemetry.lastReason=result.reason;telemetry.lastAt=new Date().toISOString();return result}catch(error:any){const result:ResearchResult={ok:false,query:q,kind,evidence:[],sources:[],reason:`SEARCH_FAILED:${clean(error?.message||error,160)}`,latencyMs:Date.now()-started,cache:'miss',attempts,sourceDiversity:0,crossChecked:false};telemetry.failures++;telemetry.lastLatencyMs=result.latencyMs;telemetry.lastReason=result.reason;telemetry.lastAt=new Date().toISOString();return result}}
