import { describe,expect,it } from 'vitest';
import { clearResearchCache, researchTelemetry, researchWeb } from '../src/web-research';
import { composeResearchAnswer } from '../src/answer-intelligence';

describe('Internet Research Engine',()=>{
  it('parses and deduplicates current news without an LLM',async()=>{const rss=`<rss><channel><item><title>ข่าวสำคัญ A - สำนักหนึ่ง</title><link>https://example.com/a</link><description>สรุปข่าวสำคัญ A</description><pubDate>${new Date().toUTCString()}</pubDate><source>สำนักหนึ่ง</source></item><item><title>ข่าวสำคัญ B - สำนักสอง</title><link>https://example.org/b</link><description>สรุปข่าวสำคัญ B</description><pubDate>${new Date().toUTCString()}</pubDate><source>สำนักสอง</source></item><item><title>ข่าวสำคัญ C - สำนักสาม</title><link>https://example.net/c</link><description>สรุปข่าวสำคัญ C</description><pubDate>${new Date().toUTCString()}</pubDate><source>สำนักสาม</source></item></channel></rss>`;const fetcher=async()=>new Response(rss,{status:200});const r=await researchWeb('ข่าวเด่น 3 เรื่องวันนี้',{kind:'news',limit:3,fetcher:fetcher as any});expect(r.ok).toBe(true);expect(r.evidence).toHaveLength(3);const answer=composeResearchAnswer(r,3);expect(answer.displayText).toContain('3 เรื่องเด่น');expect(answer.spokenText).toContain('เรื่องที่ 1');expect(answer.sources).toHaveLength(3)});
  it('parses DuckDuckGo HTML for general web research',async()=>{const html=`<div class="result results_links web-result"><h2><a class="result__a" href="https://example.com/page">Example Result</a></h2><a class="result__snippet">Useful concise evidence.</a></div>`;const fetcher=async()=>new Response(html,{status:200});const r=await researchWeb('ตัวอย่างข้อมูล',{kind:'web',limit:3,fetcher:fetcher as any,disableCache:true});expect(r.ok).toBe(true);expect(r.evidence[0]?.title).toBe('Example Result')});
  it('caches repeated searches inside a worker isolate',async()=>{clearResearchCache();let calls=0;const html=`<div class="result results_links web-result"><h2><a class="result__a" href="https://cache.example/page">Cached Result</a></h2><a class="result__snippet">Cached evidence.</a></div>`;const fetcher=async()=>{calls++;return new Response(html,{status:200})};const a=await researchWeb('cache test',{kind:'web',fetcher:fetcher as any,cacheTtlMs:60000});const b=await researchWeb('cache test',{kind:'web',fetcher:fetcher as any,cacheTtlMs:60000});expect(a.cache).toBe('miss');expect(b.cache).toBe('hit');expect(calls).toBe(1);expect(researchTelemetry().cacheHits).toBeGreaterThan(0)});
  it('retries transient failures and reports source diversity for cross-checking',async()=>{clearResearchCache();let calls=0;const rss=`<rss><channel><item><title>ข่าวทดสอบหนึ่ง</title><link>https://one.example/a</link><description>ข่าวทดสอบหนึ่ง</description><pubDate>${new Date().toUTCString()}</pubDate><source>One</source></item><item><title>ข่าวทดสอบสอง</title><link>https://two.example/b</link><description>ข่าวทดสอบสอง</description><pubDate>${new Date().toUTCString()}</pubDate><source>Two</source></item></channel></rss>`;const ddg=`<div class="result results_links web-result"><a class="result__a" href="https://three.example/c">C</a><a class="result__snippet">c</a></div>`;const fetcher=async(url:any)=>{calls++;if(calls===1)throw new Error('temporary');return new Response(String(url).includes('news.google.com')?rss:ddg,{status:200})};const r=await researchWeb('ข่าวทดสอบ',{kind:'news',limit:3,fetcher:fetcher as any,retries:1,disableCache:true});expect(r.ok).toBe(true);expect(r.attempts).toBeGreaterThanOrEqual(2);expect(r.sourceDiversity).toBeGreaterThanOrEqual(2);expect(r.crossChecked).toBe(true)});
});
