-- Ceo membership, support, credit, and presence extension for the existing
-- Personal MCP Supabase project. This migration is additive and never touches
-- auth.users credentials.

begin;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists supabase_vault with schema vault;

do $$
begin
  if not exists (select 1 from vault.secrets where name = 'ceo_support_hmac_v1') then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'ceo_support_hmac_v1',
      'Deterministic Ceo support key HMAC secret'
    );
  end if;
end;
$$;

create or replace function public.ceo_protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Keep SQL-editor/maintenance operations possible. Authenticated API callers
  -- must be an approved admin, or may change display_name on their own row only.
  if auth.uid() is null or public.is_admin(auth.uid()) then
    return new;
  end if;

  if old.id = auth.uid()
     and new.id is not distinct from old.id
     and new.email is not distinct from old.email
     and new.status is not distinct from old.status
     and new.role is not distinct from old.role
     and new.support_status is not distinct from old.support_status
     and new.approved_at is not distinct from old.approved_at
     and new.approved_by is not distinct from old.approved_by
     and new.created_at is not distinct from old.created_at then
    return new;
  end if;

  raise exception 'Only display_name may be changed by a member'
    using errcode = '42501';
end;
$$;

drop trigger if exists profiles_ceo_protect_fields on public.profiles;
create trigger profiles_ceo_protect_fields
before update on public.profiles
for each row execute procedure public.ceo_protect_profile_fields();

create table if not exists public.support_licenses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  normalized_email text not null unique check (normalized_email = lower(btrim(normalized_email))),
  key_fingerprint text not null,
  key_version integer not null default 1 check (key_version > 0),
  status text not null default 'ISSUED' check (status in ('ISSUED','ACTIVE','SUSPENDED','REVOKED')),
  plan text not null default 'UNLIMITED' check (plan = 'UNLIMITED'),
  issued_at timestamptz not null default now(),
  issued_by uuid references auth.users(id),
  activated_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_wallet (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance bigint not null default 0 check (balance >= 0),
  total_earned bigint not null default 0 check (total_earned >= 0),
  total_spent bigint not null default 0 check (total_spent >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null check (amount <> 0),
  transaction_type text not null check (transaction_type in ('WELCOME_CREDIT','SPEND','RESERVE','REFUND','ADMIN_GRANT','ADMIN_REMOVE')),
  reason text not null default '',
  balance_after bigint not null check (balance_after >= 0),
  idempotency_key text not null,
  actor_user_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (user_id, idempotency_key)
);

create index if not exists credit_transactions_user_created_idx
  on public.credit_transactions(user_id, created_at desc);

create table if not exists public.member_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  session_started_at timestamptz not null default now(),
  app_version text not null default ''
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id),
  target_user_id uuid references auth.users(id),
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log(created_at desc);

create or replace function public.ceo_touch_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists support_licenses_touch_updated_at on public.support_licenses;
create trigger support_licenses_touch_updated_at
before update on public.support_licenses
for each row execute procedure public.ceo_touch_updated_at();

create or replace function public.ceo_member_snapshot()
returns table (
  user_id uuid,
  email text,
  display_name text,
  account_status text,
  account_role text,
  support_status text,
  support_plan text,
  credit_balance bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.email, p.display_name, p.status::text, p.role::text,
         coalesce(l.status, 'NOT_ACTIVATED'),
         case when l.status = 'ACTIVE' then l.plan else null end,
         coalesce(w.balance, 0)
    from public.profiles p
    left join public.support_licenses l on l.user_id = p.id
    left join public.credit_wallet w on w.user_id = p.id
   where p.id = auth.uid();
$$;

create or replace function public.ceo_membership_capabilities()
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object('schema_version', 1, 'presence_threshold_seconds', 120);
$$;

create or replace function public.ceo_initialize_member()
returns table (
  user_id uuid,
  email text,
  display_name text,
  account_status text,
  account_role text,
  support_status text,
  support_plan text,
  credit_balance bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select p.status::text into profile_status
    from public.profiles p where p.id = auth.uid();
  if profile_status is null then
    raise exception 'Member profile not found' using errcode = 'P0002';
  end if;

  if profile_status = 'approved' then
    insert into public.credit_wallet(user_id)
    values (auth.uid()) on conflict (user_id) do nothing;
  end if;

  return query select * from public.ceo_member_snapshot();
end;
$$;

create or replace function public.ceo_support_key(normalized_email text, key_version integer default 1)
returns text
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  secret text;
  encoded text;
begin
  select decrypted_secret into secret
    from vault.decrypted_secrets
   where name = 'ceo_support_hmac_v1'
   order by created_at desc limit 1;
  if coalesce(secret, '') = '' then
    raise exception 'Ceo support HMAC secret is not configured';
  end if;
  encoded := upper(encode(extensions.hmac(
    convert_to('ceo-support:v' || key_version || ':' || lower(btrim(normalized_email)), 'utf8'),
    convert_to(secret, 'utf8'), 'sha256'), 'hex'));
  return 'CEO-' || substr(encoded,1,4) || '-' || substr(encoded,5,4) || '-' || substr(encoded,9,4);
end;
$$;

create or replace function public.ceo_admin_find_member(search_email text)
returns table (user_id uuid, email text, account_status text, account_role text, can_generate boolean)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.email, p.status::text, p.role::text, p.status = 'approved'
    from public.profiles p
   where public.is_admin(auth.uid())
     and lower(btrim(p.email)) = lower(btrim(search_email))
   limit 1;
$$;

create or replace function public.ceo_admin_generate_support(search_email text)
returns table (user_id uuid, email text, support_key text, license_status text, support_plan text)
language plpgsql
security definer
set search_path = public
as $$
declare
  target public.profiles%rowtype;
  normalized text := lower(btrim(search_email));
  raw_key text;
  fingerprint text;
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Approved admin required' using errcode = '42501';
  end if;
  select * into target from public.profiles p
   where lower(btrim(p.email)) = normalized limit 1;
  if target.id is null then
    raise exception 'Account not found' using errcode = 'P0002';
  end if;
  if target.status <> 'approved' then
    raise exception 'Account is not approved' using errcode = '42501';
  end if;

  raw_key := public.ceo_support_key(normalized, 1);
  fingerprint := encode(extensions.digest(convert_to(raw_key, 'utf8'), 'sha256'), 'hex');
  insert into public.support_licenses(user_id, normalized_email, key_fingerprint, key_version, issued_by)
  values (target.id, normalized, fingerprint, 1, auth.uid())
  on conflict (user_id) do update
    set normalized_email = excluded.normalized_email,
        key_fingerprint = excluded.key_fingerprint,
        key_version = excluded.key_version,
        issued_by = coalesce(public.support_licenses.issued_by, excluded.issued_by);

  insert into public.admin_audit_log(actor_user_id, target_user_id, action, metadata)
  values (auth.uid(), target.id, 'SUPPORT_GENERATE', jsonb_build_object('key_version', 1));

  return query
    select target.id, target.email, raw_key, l.status, l.plan
      from public.support_licenses l where l.user_id = target.id;
end;
$$;

create or replace function public.ceo_activate_support(submitted_key text)
returns table (support_status text, support_plan text, activated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized text;
  fingerprint text;
  license public.support_licenses%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  select lower(btrim(p.email)) into normalized from public.profiles p where p.id = auth.uid();
  fingerprint := encode(extensions.digest(convert_to(upper(btrim(submitted_key)), 'utf8'), 'sha256'), 'hex');
  select * into license from public.support_licenses l where l.user_id = auth.uid() for update;
  if license.id is null or license.normalized_email <> normalized or license.key_fingerprint <> fingerprint then
    raise exception 'Support key does not match this account' using errcode = '42501';
  end if;
  if license.status not in ('ISSUED','ACTIVE') then
    raise exception 'Support license is not activatable' using errcode = '42501';
  end if;
  update public.support_licenses
     set status = 'ACTIVE', activated_at = coalesce(activated_at, now()), revoked_at = null
   where id = license.id;
  insert into public.admin_audit_log(actor_user_id, target_user_id, action)
  values (auth.uid(), auth.uid(), 'SUPPORT_ACTIVATE');
  return query select l.status, l.plan, l.activated_at
    from public.support_licenses l where l.id = license.id;
end;
$$;

create or replace function public.ceo_admin_set_support(target_user uuid, next_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare normalized_status text := upper(btrim(next_status));
begin
  if not public.is_admin(auth.uid()) then
    raise exception 'Approved admin required' using errcode = '42501';
  end if;
  if normalized_status not in ('ACTIVE','SUSPENDED','REVOKED') then
    raise exception 'Invalid support status';
  end if;
  update public.support_licenses
     set status = normalized_status,
         revoked_at = case when normalized_status = 'REVOKED' then now() else null end,
         activated_at = case when normalized_status = 'ACTIVE' then coalesce(activated_at, now()) else activated_at end
   where user_id = target_user;
  if not found then raise exception 'Support license not found' using errcode = 'P0002'; end if;
  insert into public.admin_audit_log(actor_user_id, target_user_id, action)
  values (auth.uid(), target_user, 'SUPPORT_' || normalized_status);
end;
$$;

create or replace function public.ceo_credit_apply(
  target_user uuid,
  signed_amount bigint,
  tx_type text,
  tx_reason text,
  request_key text,
  actor uuid
)
returns table (balance bigint, unlimited boolean, repeated boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_balance bigint;
  prior_balance bigint;
  is_unlimited boolean;
begin
  if coalesce(btrim(request_key), '') = '' then raise exception 'Idempotency key required'; end if;
  select t.balance_after into prior_balance from public.credit_transactions t
   where t.user_id = target_user and t.idempotency_key = request_key;
  if found then return query select prior_balance, false, true; return; end if;

  select exists(select 1 from public.support_licenses l where l.user_id = target_user and l.status = 'ACTIVE')
    into is_unlimited;
  if is_unlimited and signed_amount < 0 then
    select coalesce(w.balance,0) into current_balance from public.credit_wallet w where w.user_id = target_user;
    return query select coalesce(current_balance,0), true, false; return;
  end if;

  insert into public.credit_wallet(user_id) values (target_user) on conflict (user_id) do nothing;
  select w.balance into current_balance from public.credit_wallet w where w.user_id = target_user for update;
  if current_balance + signed_amount < 0 then
    raise exception 'Insufficient credit' using errcode = '22003';
  end if;
  update public.credit_wallet
     set balance = balance + signed_amount,
         total_earned = total_earned + greatest(signed_amount, 0),
         total_spent = total_spent + greatest(-signed_amount, 0),
         updated_at = now()
   where user_id = target_user returning credit_wallet.balance into current_balance;
  insert into public.credit_transactions(user_id, amount, transaction_type, reason, balance_after, idempotency_key, actor_user_id)
  values (target_user, signed_amount, tx_type, coalesce(tx_reason,''), current_balance, request_key, actor);
  return query select current_balance, false, false;
end;
$$;

create or replace function public.ceo_spend_credit(amount bigint, reason text, idempotency_key text)
returns table (balance bigint, unlimited boolean, repeated boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or amount <= 0 then raise exception 'Invalid credit spend'; end if;
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.status='approved') then
    raise exception 'Approved account required' using errcode = '42501';
  end if;
  return query select * from public.ceo_credit_apply(auth.uid(), -amount, 'SPEND', reason, idempotency_key, auth.uid());
end;
$$;

create or replace function public.ceo_reserve_credit(amount bigint, reason text, idempotency_key text)
returns table (balance bigint, unlimited boolean, repeated boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or amount <= 0 then raise exception 'Invalid credit reserve'; end if;
  if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.status='approved') then
    raise exception 'Approved account required' using errcode = '42501';
  end if;
  return query select * from public.ceo_credit_apply(auth.uid(), -amount, 'RESERVE', reason, idempotency_key, auth.uid());
end;
$$;

create or replace function public.ceo_admin_adjust_credit(target_user uuid, amount bigint, reason text, idempotency_key text)
returns table (balance bigint, unlimited boolean, repeated boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then raise exception 'Approved admin required' using errcode = '42501'; end if;
  if amount = 0 then raise exception 'Credit adjustment cannot be zero'; end if;
  return query select * from public.ceo_credit_apply(
    target_user, amount, case when amount > 0 then 'ADMIN_GRANT' else 'ADMIN_REMOVE' end,
    reason, idempotency_key, auth.uid());
  insert into public.admin_audit_log(actor_user_id, target_user_id, action, metadata)
  values (auth.uid(), target_user, case when amount > 0 then 'CREDIT_GRANT' else 'CREDIT_REMOVE' end,
          jsonb_build_object('amount', amount, 'idempotency_key', idempotency_key));
end;
$$;

create or replace function public.ceo_admin_refund_credit(target_user uuid, amount bigint, reason text, idempotency_key text)
returns table (balance bigint, unlimited boolean, repeated boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin(auth.uid()) then raise exception 'Approved admin required' using errcode = '42501'; end if;
  if amount <= 0 then raise exception 'Refund amount must be positive'; end if;
  return query select * from public.ceo_credit_apply(target_user, amount, 'REFUND', reason, idempotency_key, auth.uid());
  insert into public.admin_audit_log(actor_user_id, target_user_id, action, metadata)
  values (auth.uid(), target_user, 'CREDIT_REFUND', jsonb_build_object('amount', amount, 'idempotency_key', idempotency_key));
end;
$$;

create or replace function public.ceo_presence_heartbeat(client_version text, session_started timestamptz default now())
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  insert into public.member_presence(user_id, last_seen_at, session_started_at, app_version)
  values (auth.uid(), now(), coalesce(session_started,now()), left(coalesce(client_version,''),64))
  on conflict (user_id) do update
    set last_seen_at=now(), session_started_at=excluded.session_started_at, app_version=excluded.app_version;
end;
$$;

create or replace function public.ceo_admin_presence_roster()
returns table (user_id uuid, email text, account_status text, online boolean, last_seen_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.email, p.status::text,
         coalesce(mp.last_seen_at >= now() - interval '2 minutes', false),
         mp.last_seen_at
    from public.profiles p
    left join public.member_presence mp on mp.user_id = p.id
   where public.is_admin(auth.uid())
   order by coalesce(mp.last_seen_at >= now() - interval '2 minutes', false) desc,
            lower(p.email);
$$;

alter table public.support_licenses enable row level security;
alter table public.credit_wallet enable row level security;
alter table public.credit_transactions enable row level security;
alter table public.member_presence enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists "member read own support" on public.support_licenses;
create policy "member read own support" on public.support_licenses for select to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));
drop policy if exists "member read own wallet" on public.credit_wallet;
create policy "member read own wallet" on public.credit_wallet for select to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));
drop policy if exists "member read own credit transactions" on public.credit_transactions;
create policy "member read own credit transactions" on public.credit_transactions for select to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));
drop policy if exists "admin read audit log" on public.admin_audit_log;
create policy "admin read audit log" on public.admin_audit_log for select to authenticated
using (public.is_admin(auth.uid()));

revoke all on public.support_licenses, public.credit_wallet, public.credit_transactions,
  public.member_presence, public.admin_audit_log from anon;
revoke insert, update, delete on public.support_licenses, public.credit_wallet,
  public.credit_transactions, public.member_presence, public.admin_audit_log from authenticated;
grant select on public.support_licenses, public.credit_wallet, public.credit_transactions,
  public.admin_audit_log to authenticated;

revoke all on function public.ceo_support_key(text, integer) from public, anon, authenticated;
revoke all on function public.ceo_credit_apply(uuid, bigint, text, text, text, uuid) from public, anon, authenticated;
grant execute on function public.ceo_member_snapshot(), public.ceo_initialize_member(),
  public.ceo_admin_find_member(text), public.ceo_admin_generate_support(text),
  public.ceo_activate_support(text), public.ceo_admin_set_support(uuid,text),
  public.ceo_spend_credit(bigint,text,text), public.ceo_reserve_credit(bigint,text,text),
  public.ceo_admin_adjust_credit(uuid,bigint,text,text), public.ceo_admin_refund_credit(uuid,bigint,text,text),
  public.ceo_presence_heartbeat(text,timestamptz), public.ceo_admin_presence_roster()
to authenticated;
grant execute on function public.ceo_membership_capabilities() to anon, authenticated;

commit;
